force-app/main/default/objects/Oferta_pracy__c/Oferta_pracy__c.object-meta.xml
<CustomObject>
    <description>Oferta pracy</description>
    <label>Oferta pracy</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Numer Oferty</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oferty pracy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Oferta_pracy__c/fields/Menedzer_rekrutujacy__c.field-meta.xml
<CustomField>
    <fullName>Menedzer_rekrutujacy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Menedżer odpowiedzialny za rekrutacje</description>
    <inlineHelpText>Menedżer odpowiedzialny za rekrutacje</inlineHelpText>
    <label>Menedżer rekrutujący</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oferty_pracy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OfertaPracyTriggerHandler.cls
public with sharing class OfertaPracyTriggerHandler {
    public static void run(List<Oferta_Pracy__c> newList, Map<Id, Oferta_Pracy__c> oldMap, Boolean isInsert, Boolean isUpdate) {

        List<Oferta_Pracy__c> toProcess = new List<Oferta_Pracy__c>();
        for (Oferta_Pracy__c o : newList) {
            if (isInsert) {
                toProcess.add(o);
            } else if (isUpdate) {
                Oferta_Pracy__c oldO = oldMap.get(o.Id);
                if (o.Menedzer_rekrutujacy__c != oldO.Menedzer_rekrutujacy__c) {
                    toProcess.add(o);
                }
            }
        }

        if (!toProcess.isEmpty()) {
            OfertaPracyShareService.syncShares(toProcess, oldMap);
            KandydatShareService.syncForOffers(toProcess, oldMap);
        }
    }
}